const sample_data = {
  meta: {
    generated_at: '2025-12-14T10:26:52.693Z',
    filters_applied: {
      enhanced_only: false,
      min_confidence: 45,
    },
    total_predictions_analyzed: 64,
    sections_returned: ['by_outcome', 'overall', 'hottest'],
  },
  by_outcome: {
    home_win: [
      {
        fixture_id: 1388426,
        home_team: 'Bayern München',
        away_team: 'FSV Mainz 05',
        league_id: 78,
        season: 2025,
        outcome: 'Home Win',
        outcome_probability: 65,
        outcome_confidence: 77,
        computed_score: 69.2,
        confidence_level: 'HIGH',
        confidence_overall: 77,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:33.505Z',
      },
      {
        fixture_id: 1381003,
        home_team: 'AZ Alkmaar',
        away_team: 'Excelsior',
        league_id: 88,
        season: 2025,
        outcome: 'Home Win',
        outcome_probability: 52,
        outcome_confidence: 69,
        computed_score: 57.95,
        confidence_level: 'MEDIUM',
        confidence_overall: 69,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:38.771Z',
      },
      {
        fixture_id: 1387836,
        home_team: 'Lyon',
        away_team: 'Le Havre',
        league_id: 61,
        season: 2025,
        outcome: 'Home Win',
        outcome_probability: 50,
        outcome_confidence: 70,
        computed_score: 57,
        confidence_level: 'MEDIUM',
        confidence_overall: 70,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:51.222Z',
      },
    ],
    draw: [
      {
        fixture_id: 1382762,
        home_team: 'Aberdeen',
        away_team: 'Kilmarnock',
        league_id: 179,
        season: 2025,
        outcome: 'Draw',
        outcome_probability: 41,
        outcome_confidence: 76,
        computed_score: 53.25,
        confidence_level: 'HIGH',
        confidence_overall: 76,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:59.834Z',
      },
      {
        fixture_id: 1394571,
        home_team: 'Fatih Karagümrük',
        away_team: 'Kocaelispor',
        league_id: 203,
        season: 2025,
        outcome: 'Draw',
        outcome_probability: 43,
        outcome_confidence: 71,
        computed_score: 52.8,
        confidence_level: 'MEDIUM',
        confidence_overall: 71,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:45:15.992Z',
      },
      {
        fixture_id: 1382767,
        home_team: 'Rangers',
        away_team: 'Hibernian',
        league_id: 179,
        season: 2025,
        outcome: 'Draw',
        outcome_probability: 37,
        outcome_confidence: 76,
        computed_score: 50.65,
        confidence_level: 'HIGH',
        confidence_overall: 76,
        enhanced: true,
        prediction_created_at: '2025-12-14T09:30:11.512Z',
      },
    ],
    away_win: [
      {
        fixture_id: 1378007,
        home_team: 'Genoa',
        away_team: 'Inter',
        league_id: 135,
        season: 2025,
        outcome: 'Away Win',
        outcome_probability: 51,
        outcome_confidence: 72,
        computed_score: 58.35,
        confidence_level: 'MEDIUM',
        confidence_overall: 67,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:45:11.740Z',
      },
      {
        fixture_id: 1379126,
        home_team: 'Nottingham Forest',
        away_team: 'Tottenham',
        league_id: 39,
        season: 2025,
        outcome: 'Away Win',
        outcome_probability: 46,
        outcome_confidence: 68,
        computed_score: 53.7,
        confidence_level: 'MEDIUM',
        confidence_overall: 68,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:57.062Z',
      },
      {
        fixture_id: 1387834,
        home_team: 'Auxerre',
        away_team: 'Lille',
        league_id: 61,
        season: 2025,
        outcome: 'Away Win',
        outcome_probability: 47,
        outcome_confidence: 66,
        computed_score: 53.65,
        confidence_level: 'MEDIUM',
        confidence_overall: 66,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:52.757Z',
      },
    ],
    btts_yes: [
      {
        fixture_id: 1388429,
        home_team: 'SC Freiburg',
        away_team: 'Borussia Dortmund',
        league_id: 78,
        season: 2025,
        outcome: 'BTTS Yes',
        outcome_probability: 77,
        outcome_confidence: 75,
        computed_score: 76.3,
        confidence_level: 'MEDIUM',
        confidence_overall: 70,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:32.840Z',
      },
      {
        fixture_id: 1381003,
        home_team: 'AZ Alkmaar',
        away_team: 'Excelsior',
        league_id: 88,
        season: 2025,
        outcome: 'BTTS Yes',
        outcome_probability: 77,
        outcome_confidence: 74,
        computed_score: 75.95,
        confidence_level: 'MEDIUM',
        confidence_overall: 69,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:38.771Z',
      },
      {
        fixture_id: 1381002,
        home_team: 'Ajax',
        away_team: 'Feyenoord',
        league_id: 88,
        season: 2025,
        outcome: 'BTTS Yes',
        outcome_probability: 74,
        outcome_confidence: 73,
        computed_score: 73.65,
        confidence_level: 'MEDIUM',
        confidence_overall: 68,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:42.079Z',
      },
    ],
    over_2_5: [
      {
        fixture_id: 1388426,
        home_team: 'Bayern München',
        away_team: 'FSV Mainz 05',
        league_id: 78,
        season: 2025,
        outcome: 'Over 2.5',
        outcome_probability: 76,
        outcome_confidence: 82,
        computed_score: 78.1,
        confidence_level: 'HIGH',
        confidence_overall: 77,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:33.505Z',
      },
      {
        fixture_id: 1387837,
        home_team: 'Marseille',
        away_team: 'Monaco',
        league_id: 61,
        season: 2025,
        outcome: 'Over 2.5',
        outcome_probability: 71,
        outcome_confidence: 66,
        computed_score: 69.25,
        confidence_level: 'MEDIUM',
        confidence_overall: 66,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:54.110Z',
      },
      {
        fixture_id: 1388429,
        home_team: 'SC Freiburg',
        away_team: 'Borussia Dortmund',
        league_id: 78,
        season: 2025,
        outcome: 'Over 2.5',
        outcome_probability: 63,
        outcome_confidence: 70,
        computed_score: 65.45,
        confidence_level: 'MEDIUM',
        confidence_overall: 70,
        enhanced: true,
        prediction_created_at: '2025-12-13T10:44:32.840Z',
      },
    ],
  },
  overall: [
    {
      fixture_id: 1388426,
      home_team: 'Bayern München',
      away_team: 'FSV Mainz 05',
      league_id: 78,
      season: 2025,
      outcome: 'Home Win',
      outcome_probability: 65,
      outcome_confidence: 77,
      computed_score: 57.8,
      confidence_level: 'HIGH',
      confidence_overall: 77,
      enhanced: true,
      prediction_created_at: '2025-12-13T10:44:33.505Z',
    },
    {
      fixture_id: 1381003,
      home_team: 'AZ Alkmaar',
      away_team: 'Excelsior',
      league_id: 88,
      season: 2025,
      outcome: 'Home Win',
      outcome_probability: 52,
      outcome_confidence: 69,
      computed_score: 49.7,
      confidence_level: 'MEDIUM',
      confidence_overall: 69,
      enhanced: true,
      prediction_created_at: '2025-12-13T10:44:38.771Z',
    },
    {
      fixture_id: 1378007,
      home_team: 'Genoa',
      away_team: 'Inter',
      league_id: 135,
      season: 2025,
      outcome: 'Away Win',
      outcome_probability: 51,
      outcome_confidence: 72,
      computed_score: 48.8,
      confidence_level: 'MEDIUM',
      confidence_overall: 67,
      enhanced: true,
      prediction_created_at: '2025-12-13T10:45:11.740Z',
    },
  ],
  hottest: [
    {
      fixture_id: 1388426,
      home_team: 'Bayern München',
      away_team: 'FSV Mainz 05',
      league_id: 78,
      season: 2025,
      outcome: 'Over 2.5',
      outcome_probability: 76,
      outcome_confidence: 82,
      computed_score: 57.8,
      confidence_level: 'HIGH',
      confidence_overall: 77,
      enhanced: true,
      prediction_created_at: '2025-12-13T10:44:33.505Z',
      hot_score: 62.95,
      score_breakdown: {
        confidence_contribution: 19.25,
        probability_contribution: 13,
        top_outcome_contribution: 27.5,
        stability_bonus: 6.1,
        variance_penalty: -3.9,
        other_bonuses: 8,
        other_penalties: 0,
      },
      form_stability: 61,
      avg_variance: 39,
      reducing_factors: [
        'FSV Mainz 05 inconsistent form (67% variance) - unpredictable performer',
      ],
    },
    {
      fixture_id: 1381003,
      home_team: 'AZ Alkmaar',
      away_team: 'Excelsior',
      league_id: 88,
      season: 2025,
      outcome: 'BTTS Yes',
      outcome_probability: 77,
      outcome_confidence: 74,
      computed_score: 49.7,
      confidence_level: 'MEDIUM',
      confidence_overall: 69,
      enhanced: true,
      prediction_created_at: '2025-12-13T10:44:38.771Z',
      hot_score: 53.91,
      score_breakdown: {
        confidence_contribution: 17.25,
        probability_contribution: 10.4,
        top_outcome_contribution: 26.5,
        stability_bonus: 3.9,
        variance_penalty: -6.15,
        other_bonuses: 8,
        other_penalties: 0,
      },
      form_stability: 39,
      avg_variance: 61.5,
      reducing_factors: [
        'Excelsior inconsistent form (67% variance) - unpredictable performer',
        'Both teams showing volatile form - momentum difficult to assess',
      ],
    },
    {
      fixture_id: 1388429,
      home_team: 'SC Freiburg',
      away_team: 'Borussia Dortmund',
      league_id: 78,
      season: 2025,
      outcome: 'BTTS Yes',
      outcome_probability: 77,
      outcome_confidence: 75,
      computed_score: 41.8,
      confidence_level: 'MEDIUM',
      confidence_overall: 70,
      enhanced: true,
      prediction_created_at: '2025-12-13T10:44:32.840Z',
      hot_score: 52.33,
      score_breakdown: {
        confidence_contribution: 17.5,
        probability_contribution: 7.2,
        top_outcome_contribution: 26.65,
        stability_bonus: 4.4,
        variance_penalty: -5.6,
        other_bonuses: 8,
        other_penalties: 0,
      },
      form_stability: 44,
      avg_variance: 56,
      reducing_factors: [
        'Both teams showing volatile form - momentum difficult to assess',
      ],
    },
    {
      fixture_id: 1382762,
      home_team: 'Aberdeen',
      away_team: 'Kilmarnock',
      league_id: 179,
      season: 2025,
      outcome: 'BTTS Yes',
      outcome_probability: 48,
      outcome_confidence: 76,
      computed_score: 44.7,
      confidence_level: 'HIGH',
      confidence_overall: 76,
      enhanced: true,
      prediction_created_at: '2025-12-13T10:44:59.834Z',
      hot_score: 51.62,
      score_breakdown: {
        confidence_contribution: 19,
        probability_contribution: 8.2,
        top_outcome_contribution: 21,
        stability_bonus: 5.6,
        variance_penalty: -4.45,
        other_bonuses: 8,
        other_penalties: 0,
      },
      form_stability: 56,
      avg_variance: 44.5,
      reducing_factors: [],
    },
    {
      fixture_id: 1382567,
      home_team: 'Charleroi',
      away_team: 'Union St. Gilloise',
      league_id: 144,
      season: 2025,
      outcome: 'BTTS Yes',
      outcome_probability: 47,
      outcome_confidence: 76,
      computed_score: 43.6,
      confidence_level: 'HIGH',
      confidence_overall: 76,
      enhanced: true,
      prediction_created_at: '2025-12-13T10:44:45.732Z',
      hot_score: 50.94,
      score_breakdown: {
        confidence_contribution: 19,
        probability_contribution: 7.6,
        top_outcome_contribution: 20.8,
        stability_bonus: 5.6,
        variance_penalty: -4.4,
        other_bonuses: 8,
        other_penalties: 0,
      },
      form_stability: 56,
      avg_variance: 44,
      reducing_factors: [],
    },
  ],
};
